/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ServicosNovoRouteImport } from './routes/servicos.novo'
import { Route as ServicosIdIndexRouteImport } from './routes/servicos.$id.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosNovoRoute = ServicosNovoRouteImport.update({
  id: '/servicos/novo',
  path: '/servicos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIdIndexRoute = ServicosIdIndexRouteImport.update({
  id: '/servicos/$id/',
  path: '/servicos/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servicos/novo': typeof ServicosNovoRoute
  '/servicos/': typeof ServicosIndexRoute
  '/servicos/$id/': typeof ServicosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servicos/novo': typeof ServicosNovoRoute
  '/servicos': typeof ServicosIndexRoute
  '/servicos/$id': typeof ServicosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servicos/novo': typeof ServicosNovoRoute
  '/servicos/': typeof ServicosIndexRoute
  '/servicos/$id/': typeof ServicosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/servicos/novo' | '/servicos/' | '/servicos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servicos/novo' | '/servicos' | '/servicos/$id'
  id: '__root__' | '/' | '/servicos/novo' | '/servicos/' | '/servicos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicosNovoRoute: typeof ServicosNovoRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
  ServicosIdIndexRoute: typeof ServicosIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/novo': {
      id: '/servicos/novo'
      path: '/servicos/novo'
      fullPath: '/servicos/novo'
      preLoaderRoute: typeof ServicosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$id/': {
      id: '/servicos/$id/'
      path: '/servicos/$id'
      fullPath: '/servicos/$id/'
      preLoaderRoute: typeof ServicosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicosNovoRoute: ServicosNovoRoute,
  ServicosIndexRoute: ServicosIndexRoute,
  ServicosIdIndexRoute: ServicosIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
